spring:
  application:
    name: travelcompass
  profiles:
    active: local   # 기본 실행 프로필. 배포 시 --spring.profiles.active=prod 로 오버라이드
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.travelcompass.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.example.travelcompass: debug
